### ISSUE TITLE
Repeatedly asking to save swoopBuf for each key press.

### ISSUE THREAD

**Issue by darkshadow** [pelodelfuego/vim-swoop#13] opened 2015-01-15 14:13 UTC
For each key press I am getting this message:
```
Save changes to "swoopBuf"?
[Y]es, (N)o, (C)ancel:
```
Doesn't matter if I save after entering another character in swoopbuf I am getting asked the same thing. Sometimes I am seeing additional error below.
```
Error detected while processing function <SNR>21_cursorMoved..<SNR>21_displaySwoopResult..<SNR>21_getSwoopResultsLine:
line    5:
E37: No write since last change (add ! to override)
```

Additional info about the vim that I am using.
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 27 2014 04:39:22)
MacOS X (unix) version
Included patches: 1-488
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: /usr/bin/clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib  -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa  -L/usr/local/lib -llua -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.2.0 -lgmp -lobjc -L/Users/darkshadow/.rvm/rubies/ruby-2.2.0/lib   

```

**Comment by pelodelfuego** [comment] 2015-01-15 14:33
Hello, 
Can you post me your .vimrc and the list of plugin you use ?

It may be caused by an Autocmd somewhere.

**Comment by darkshadow** [comment] 2015-01-15 14:35
Here is my .vimrc

```
set nocompatible              " be iMproved, required
filetype off                  " required
syntax off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
    " alternatively, pass a path where Vundle should install plugins
    "call vundle#begin('~/some/path/here')

    " let Vundle manage Vundle, required
    Plugin 'gmarik/Vundle.vim'

    "ctrlp plugin
    Plugin 'kien/ctrlp.vim'

    "vim swoop
    Plugin 'pelodelfuego/vim-swoop'

    " live script support
    "Plugin 'gkz/vim-ls'

    "js completion using tern server
    Plugin 'marijnh/tern_for_vim'
    
    "syntax check using external linters
    Plugin 'scrooloose/syntastic'
    
    "jade template language support
    Plugin 'digitaltoad/vim-jade'
    
    "javascript language support
    Plugin 'jelera/vim-javascript-syntax'

    "coffeescirpt language support
    Plugin 'kchmck/vim-coffee-script'

    "less langauge support
    Plugin 'groenewege/vim-less'


    "Auto complete support
    Plugin 'Shougo/neocomplete.vim'


    "disable because running out of memory on vagrant ubuntu vm
    "Plugin 'Valloric/YouCompleteMe'

    "Plugin 'godlygeek/tabular'
    "Plugin 'Raimondi/delimitMate'

    "Modern looking status bar support
    Plugin 'bling/vim-airline'

    "ctags based plugin to easily view symbols in current file
    Plugin 'majutsushi/tagbar'
    
    "Plugin 'zenorocha/dracula-theme'
    "Plugin 'altercation/vim-colors-solarized'

    "File browser plugin
    Plugin 'scrooloose/nerdtree',

    "Alternative to grep with commonsense
    "Bundle 'mileszs/ack.vim',

    "Golanguage support
    Plugin 'fatih/vim-go'

    "Popular color schemes support
    Plugin 'flazz/vim-colorschemes'
    

    " All of your Plugins must be added before the following line
    call vundle#end()            " required

    "filetype plugin on
    "
    " Brief help
    " :PluginList       - lists configured plugins
    " :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
    " :PluginSearch foo - searches for foo; append `!` to refresh local cache
    " :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
    "
    " see :h vundle for more details or wiki for FAQ
    " Put your non-Plugin stuff after this line

filetype plugin on
filetype indent on
set wildignore+=*/.git/*,*/node_modules/*,*/bower_components/*

let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1

let mapleader = "\<Space>"
syntax on

set nowrap
set number
"set noantialias
set directory=$HOME/.vim/swapfiles//

set gfn=Source\ Code\ Pro:h14
"set gfn=Fira\ Mono:h14
set t_Co=256
set background=dark
set omnifunc=syntaxcomplete#Complete
set nowritebackup
set laststatus=2

set completeopt=menu

colo jellybeans

nmap  <ESC><ESC> <ESC>:w!<ENTER>

"Change leader to <SPACE> inspired from spacemacs
let mapleader=" "



set ignorecase smartcase incsearch nohlsearch
set tabstop=4
set expandtab
set shiftwidth=4
set smartindent autoindent


set confirm

"Shortcuts
"show invisible chars
map <leader>l :set list!<ENTER>
map <leader>t :Tagbar<ENTER>
set listchars=tab:▸\ ,eol:¬


let g:tagbar_autofocus = 1   

```

**Comment by pelodelfuego** [comment] 2015-01-15 15:13
I can' find the cause of the issue right now, still looking.
Maybe you are using a kind of 'autosave' buffer functionality ?

**Comment by darkshadow** [comment] 2015-01-15 17:18
Not sure. I only use only this vimrc file.  I am not much expert in internals of vim.

**Comment by jonthn** [comment] 2015-01-15 23:28
Could you try adding ```set hidden``` in your vimrc ?

**Comment by darkshadow** [comment] 2015-01-15 23:35
Thanks, ```set hidden``` seems to do the trick. I no longer get the error message.

**Comment by pelodelfuego** [comment] 2015-01-16 23:25
Thank you very much jonthn =)
So i close the issue/

**Closed by pelodelfuego** 2015-01-16 23:25 UTC

**Comment by jonthn** [comment] 2015-01-16 23:45
No problem.
Still I'm not sure how to do it "the right 'vim' way" I believe it would help to take a look to plugins that do something similar (opening a window and editing in it) like "unite.vim" for Shougo or maybe undotre/tagbar but those 2 could be less relevant in this case.
