### ISSUE TITLE
Docs for set cursorline, clear input on Insert, extra char from Visual, window size

### ISSUE THREAD

**Issue by balta2ar** [pelodelfuego/vim-swoop#17] opened 2015-02-07 17:13 UTC
Hello. I've recently found this plugin and I'm trying to get used to it. Here are few issues that I've found:

1. It's almost impossible to use it without `set cursorline`. Could you please add to README.me example on how to turn on `cursorline` in all buffers (and maybe `cursorcolumn`) temporarily, while swoopBuf is present? I don't use `cursorline` all the time, but when Swoop is active, I just have to.
2. When starting Swoop, especially with default options, it goes into Insert mode. However it keeps the old search results, which is inconvenient sometimes. In this case I have to go to Normal mode, and `cc`. Could you please add an option (or make default behaviour) to clear previous search results when starting Swoop?
3. When I activate Swoop from Visual mode, for some reason it takes currently selected word **and one character next to it** which is very confusing. Is this a bug?
4. Swoop opens its buffer which takes half a screen. Sometimes that's too much. Could you please add an option to set maximum window height/width for Swoop buffer?

**Comment by pelodelfuego** [comment] 2015-02-10 13:08
Don't worry, i'll deal with you issue but not this week, i'm quiet busy.

Have a nice day.

**Comment by pelodelfuego** [comment] 2015-02-12 23:57
1. Ok, I can add an option to turn on cursor line while swoop is active

2. I don't understant the point, you do not need ```cc``` to clear old search pattern since starting typing will replace the pattern. Can you explain more ?

3. It is a bug indeed, i'll fix it

4. Sure

**Comment by pelodelfuego** [comment] 2015-02-13 00:44
1, 2, 4 Done, 
for 3 i'm waiting more info.

**Comment by balta2ar** [comment] 2015-02-13 06:01
Thank you for the fixes!

About 2. When I start Swoop and type, old search pattern is not replaced. Instead what I type is simply being inserted at the beginning of the old pattern.

Another thing I noticed: when I start Swoop from Visual mode (with selected word), it starts in Normal mode. But if I start Swoop from Normal mode, in Swoop I have Insert mode. This looks like an inconsistency.

**Comment by pelodelfuego** [comment] 2015-02-13 10:38
Thanks for your feedback
You're welcome, my pleasure to improve my plugin =)

Are you sure you didn't save someHow the ```swoopBuf``` into a file ?

Inconsistent behaviour
It is wanted, 
You have 2 use case:
- you already know what you're looking for -> selection mode
- you don't know -> you use incremental swoop as you type it

For you what would be the situation you need to start a pattern you don't know in normal mode (ie: to paste a selection) ?

**Comment by balta2ar** [comment] 2015-02-13 11:17
> Are you sure you didn't save someHow the swoopBuf into a file ?

Hmm, I'm not sure. I do `q!` or `bd!`, maybe some hook does that for me? Anyway, even if I do, it feels weird to have old results in the new search no matter what are the settings of the user. I'm used to behavior when pattern resets every time I start a new search. If you disagree, then there is another bug: the cursor is placed in the beginning of the old pattern. That is frustrating, I can't press `C-w` to erase it.

> For you what would be the situation you need to start a pattern you don't know in normal mode (ie: to paste a selection) ?

My complaint was about the mode that I start with. The docs say: `By default, you will start in insert mode`, however if I call Swoop from Visual mode, I will start in **Normal** mode. But if I call Swoop from Normal mode, yes, I will start in **Insert** mode.

**Comment by pelodelfuego** [comment] 2015-02-13 13:17
- old pattern
The point is not to save the buffer on the drive so no there is no hook as far as i know =)
What i don't understand is that there should be result of the old search but not the old pattern (see ```:h /``` 
Can you make some screenshot ?

- insert mode
You're right, i haven't update the documentation, i'll do it.

**Comment by balta2ar** [comment] 2015-02-16 08:04
I recorded a short video: http://i.imgur.com/dipJjCN.gif

**Comment by pelodelfuego** [comment] 2015-02-17 21:20
Indeed, it is not the expected behaviour.

Can you post me your vim version please ?

Until i manage to reproduce the bug, you can use this workaround:

```
let g:swoopUseDefaultKeyMap == 0
nmap <Leader>l :call Swoop()<CR>call Swoop()<CR>
nmap <Leader>ml :call SwoopMulti()<CR>call SwoopMulti()<CR>
vmap <Leader>l :call SwoopSelection()<CR>
vmap <Leader>ml :call SwoopMultiSelection()<CR>

```
It should do the trick. (calling ```Swoop()``` twice reset the pattern)

**Comment by balta2ar** [comment] 2015-02-18 08:15
My version:
```
→ vim --version                 
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 12 2015 18:02:44)
Included patches: 1-629
```
Full version: http://sprunge.us/JhVa

For some reason your workaround does not clear the input either :(

**Comment by pelodelfuego** [comment] 2015-02-18 23:06
Hum...
We will figure it out. Can you give me the list of plugin you use ?
Do you use vim session ?(maybe the swoopBuf is saved somehow)

**Comment by balta2ar** [comment] 2015-02-19 12:45
No, I don't use vimsession, at least I'm not aware of it :)

Here is a minimal vimrc: (http://sprunge.us/iNSC?vim)
``` vim
if has('vim_starting')
   set nocompatible               " Be iMproved
   set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#rc(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'pelodelfuego/vim-swoop'
NeoBundleCheck

filetype plugin indent on
syntax enable
set nocompatible
let mapleader=","
let maplocalleader=" "
```

When I use it, I get the following error messages. I think there might be other packages in my ~/.vim directory that were just copied there and are not tracked by the neobundle. If you could instruct me how to track down the culprit, I'd be glad to help.

```
Error detected while processing function <SNR>27_cursorMoved..<SNR>27_displaySwoopResult..<SNR>27_getSwoopResultsLine:
line    5:
E37: No write since last change (add ! to override)
Press ENTER or type command to continue
```

I hope that helps.

**Comment by pelodelfuego** [comment] 2015-02-20 16:26
I tried a fix on master by reverting an old "imporvement" which can cause your problem as side effect.

I didn't managed to reproduce the bug but seen it in live on a computers's friend.

Keep you in touch

**Comment by pelodelfuego** [comment] 2015-02-20 16:44
Just managed to reproduce it and the fix on the post below won't fiw the issue.

**Comment by pelodelfuego** [comment] 2015-02-20 17:29
Found it!

You need to add ```set hidden``` to your .vimrc, it allow you to hide an unsaved buffer.
I'll make a fix to avoid the issue but it is a handy option of vim.

Thanks a lot for your feed back !

Just confirm me it is ok and i close the topic.

**Comment by balta2ar** [comment] 2015-02-24 08:02
Sadly, I cannot confirm that it works now. It appears that I have and always had `set hidden` in my `.vimrc`. Still, it saves the contents. Actually, I think I found the problem, this was in my `.vimrc:

``` vim
" Autosave on buffer switch and focus lost
autocmd BufLeave,FocusLost * silent! wall
```

I disabled it and swoopBuf stopped saving its contents. But I like this feature and I don't want to turn it off because vim-swoop. Can you workaround this? It seems like a good idea to always reset search pattern when swoopBuf starts, isn't it? Or maybe add an option to do that?

Sorry for making this ticket so big, but there is another thing I'd like to mention. When you scroll over the results, it's cool that current line is selected in the preview automatically. Sometimes, though, it is a problem: if I just press `j` to scroll down over results, I can see a delay and vim slows down because vim-swoop tries to preview every line that I go through. How about adding an option: `preview_after_delay`, which default value would be 0, but if user sets it to, say, 100, preview will be shown only if user stays on the line for 100ms. What do you think?

**Comment by pelodelfuego** [comment] 2015-02-24 11:15
Ok, it makes sense that BufLeave autocommanding ```wall``` cause problem to vim-swoop:

I'll explain you a bit how it works:
We need a temp buffer (SwoopBuf) which won't be saved on drive but is savable, on saving the swoopBuf,I intercept the save command and replace occurences in buffer instead of saving the file on drive. I wish but i can't use a readlonly buffer because it doesn't provide acces to save interception.

Somehow, the autocommand you have in your .vimrc actually save the content of swoopBuf on the drive.

Now if you start swoop while a swoopBuf is saved on the drive, vim restore the content of the old swoop search. That's why you have the old search.
As i mentionned before, it is not the expected behaviour but is caused by the presence of swoopBuf saved on the drive.

I'll try to make a fix but have no idea about how to prevent save swoopBuf on the drive.

For your other suggestion, please could you open a new issue ?

**Comment by pelodelfuego** [comment] 2015-02-24 17:21
ok, you should replace:
```
autocmd BufLeave,FocusLost * silent! wall
```
by:
```
autocmd BufLeave,FocusLost * silent! nested wall
```

In default behaviour autocommand won't trigger other autocommand to avoid recursive loop. You can contourn this by adding ```nested``` to you autocommand.

Since vim-swoop use Autocommand ```BufWrite``` to avoid file write, you need to add this to trigger vim-swoop "anti-save" feature.

**Comment by balta2ar** [comment] 2015-02-27 07:54
Thanks, now it works and results are not saved!

Traditionally, here is another idea: I'm very used to Unite way of closing helper windows. When you are in Insert mode in Unite window (file_mru, file_rec, buffer, line or whatever), it filters the results. But if you press `q` in Normal mode, it closes the window. At the moment, it is a little inconvenient to close vim-swoop with `:q!` or `:bd!`. But this might be because I'm not very good with vim configuration. Do you think closing vim-swoop with simple `q` is a good idea? Otherwise, can you recommend me some other way to close it quickly?

**Comment by balta2ar** [comment] 2015-02-27 11:28
A couple of more concerns:

1. I have applied your receipt:

``` vim
augroup vimswoop
    autocmd!
    autocmd BufEnter swoopBuf set cursorline
    autocmd BufLeave swoopBuf set nocursorline
augroup end
```
And current line is highlighted but only in swoopBuf buffer. Is there any way to enable cursorline globally while swoop is active? I really miss cursorline especially in the other (original) buffer.

2. When I am in swoop buffer and I try to delete the line with `dd`, it just disappears from swoop. I don't know why, but I'd expect the line to be deleted from the file as well. This seems logical because if I change something in swoop and hit Enter, changes will be applied.

3. This one is probably hard and I'm not sure if you agree. One of the biggest reasons why I love plugins such as vim-multiple-cursors or vim-incsearch is their awesome interactivity and responsiveness. Changes are applied on the fly, this greatly improves user experience, at least for me. What do you think about making vim-swoop behave the same? Maybe optionally? Immediate changes, changes on the fly is a killer feature for me. Though this probably complicates undo support. Well, I'd like to hear your thoughts on this.

**Comment by pelodelfuego** [comment] 2015-03-01 23:20
* ```q``` to quit vim-swoop
I think it is not a good idea since ```q``` is mapped to macro reccording which is quiet handy to apply a modifiaction on swoopBuffer (see recursive macro).
To quit quickly vim-swoop, you can just change the current window ie ```C-w C-w```, it will kill swoop.

* cursorline
The latest vim-swoop version should force cursoline without tweeking your vimrc. It doesn't ?

* ```dd``` on swoopBuf
It is totally normal, if you look at the composition of a line in swoopBuf, you have:
(buf number)    (line number)    (content of line)
buffer number and line number are used to apply modification in files. If you delete a line in the swoopBuf, it will just disapear from the scope of vim-swoop.I often use this feature to exclude some matches and the apply a change to whole swoopBuf.
To delete a line, you have to replace (content of line) by (no content). this will replace the line by nothing so delete the line.

* interactivity
I don't know yet, for now the priority is to ensure stability, maybe later an option could be add, i have to think about it and indeed, the implementation will be tough =)

**Comment by balta2ar** [comment] 2015-03-02 13:37
> To quit quickly vim-swoop, you can just change the current window ie C-w C-w, it will kill swoop.

Well, I don't personally use `q` much so I could live with that. Plus, this could be configurable mapping. It's just that I'm used to `q` in Unite and `C-w C-w` takes some time to get used to. However, I don't have other strong arguments so let it be your way.

> The latest vim-swoop version should force cursoline without tweeking your vimrc. It doesn't ?

Nope. I removed your recipe and updated. cursorline is only visible in vim-swoop buffer.

> To delete a line, you have to replace (content of line) by (no content). this will replace the line by nothing so delete the line.

Hm, I've just tried it and it does not work for me. 
```
 3 1   36  extern int sparse_files;
```
I set cursor on the beginning of `extern` and pressed `d$`, then saved buffer and closed it. The line stayed.

**Comment by balta2ar** [comment] 2015-03-06 15:57
Another issue: I have two windows that are split vertically (|), I call vim-swoop from the *right* one. But when I navigate lines in swoop buffer, the *left* window gets updated, which feels unintuitive to me. Could you make it update the window from which swoop has been activated?

**Comment by balta2ar** [comment] 2015-03-06 16:11
Idea: vim-swoop only shows the lines that matched the search pattern. What if it could also add N, M lines before and after the search pattern? Just like `grep -A -B -C` do. Do you think adding such a context could be useful?

**Comment by pelodelfuego** [comment] 2015-03-16 19:17
Did you managed to replace a line by a blank line ?
(swoop is not deisnged for but it is possible)

For your split side issue, i'll take a look.

3rd idea Why not but still have higher prority like not saving buffe with no changes.

**Comment by balta2ar** [comment] 2015-03-18 08:19
Not sure if I'm doing something wrong, but line is never removed. Specifically, I tried deleting everything after line number column in vim-swoop buffer and save. It does not remove the line from the file though. However, if I leave at least one character of the original line, it gets replaced with that character as expected.

**Comment by pelodelfuego** [comment] 2015-03-19 19:08
You need to leave a \t because it is the way swoop split lines. 
If the split count is bellow 3 (buffer number, and line number, text) the line is ignored

**Comment by pelodelfuego** [comment] 2015-04-29 08:57
Can I close the issue ?

**Comment by balta2ar** [comment] 2015-04-29 09:04
Sure, I'll create another one more narrow if there is a problem. Thank you!

**Comment by pelodelfuego** [comment] 2015-04-29 12:45
Thank YOU for all your feedback !

**Closed by pelodelfuego** 2015-04-29 12:45 UTC

**Comment by ctrlok** [comment] 2015-10-16 15:21
Hi. you make a big job, thanks!
But I still don't understand how I can activate 'set cursorline' on main buffer while swoop are opened, and deactivate when I close swoop?

**Comment by jon-choi** [comment] 2016-01-15 19:43
Can we have an option to open the window as a % of your screen size? when i plug into my monitor 50% is definitely too big, but 15 rows is too small. What I really want is 25% of my screen at any given time that I open it.

Also, this plugin is amazing btw :) Thank you!
